				<div>
					<form name="mainForm" action="javascript:passwordReset()" style="width:320px; padding:0 310px 0 310px">
						<div style="clear:both; padding:0 0 5px 0;">
							<span style="float:left; padding:0 0 5px 0;">Current Password:</span>
							<input type="password" name="current_password" style="clear:none; float:right;" />
						</div>
						<div id="newPasswordDiv" style="clear:both; padding:5px 0 0 0; border-width: 1px 0 0 0; border-style: solid; border-color: #C00;">
							<div style="clear:both;">
								<span style="float:left;">New Password:</span>
								<input type="password" name="password" style="clear:none; float:right;" />
							</div>
							<div style="clear:both; margin:5px 0 0 0;">
								<span style="float:left;">Re-enter Password:</span>
								<input type="password" name="verify" style="clear:none; float:right;" />
							</div>
						</div>
						<input type="submit" value="Submit" style="float:right; clear:both; margin:5px 0 0 0;" />
					</form>
				</div>