<ul style="list-style: none outside; display: block; width: 100%;">
	<li style="display: block; float: left; width: 48%; padding: 1%;"><a href="contact.php">Update Contact Information</a>
		<div>Change, add, and remove any of your contact information</div>
	</li>
	<li style="display: block; float: left; width: 48%; padding: 1%;"><a href="password.php">Password Reset</a>
		<div>Update your password</div>
	</li>
</ul>