This is a welcome messages.
<ul style="list-style: none outside; display: block; width: 100%;">
	<li style="display: block; float: left; width: 48%; padding: 1%;"><a href="open.php">Open Tickets</a>
		<div>Check on the status of computers that you currently have checked in</div>
	</li>
	<li style="display: block; float: left; width: 48%; padding: 1%;"><a href="closed.php">Closed Tickets</a>
		<div>Review information on tickets that you have already picked Up</div>
	</li>
</ul>