		<div class="row">
			<div class="cell header" style="width:33%">Laptop Accessories</div>
			<div class="cell" style="width:33%">
				<div class="cell">
					Power Supply:
				</div>
				<div id="laptopPower" class="cell" style="padding:0 0 0 5px">{POWERSUPPLY}</div>
			</div>
			<div class="cell" style="width:1%">
				&nbsp;
			</div>
			<div class="cell" style="width:33%">
				<div class="cell">
					Case:
				</div>
				<div id="laptopCase" class="cell" style="padding:0 0 0 5px">{CASE}</div>
			</div>
		</div>
