<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" ><!-- InstanceBegin template="/Templates/php.unlstandardtemplate.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>MyCHC.unl.edu - {TITLE}</title>
<link rel="stylesheet" type="text/css" media="screen" href="/ucomm/templatedependents/templatecss/layouts/main.css" />
<link rel="stylesheet" type="text/css" media="print" href="/ucomm/templatedependents/templatecss/layouts/print.css"/>
<script type="text/javascript" src="/ucomm/templatedependents/templatesharedcode/scripts/all_compressed.js"></script>

{WEBDEVHEADERS}
<link rel="stylesheet" type="text/css" media="screen" href="/ucomm/templatedependents/templatecss/layouts/secure.css"/>
<link rel="stylesheet" href="/includes/css/main-style.css" type="text/css" />
<link rel="stylesheet" href="includes/css/main-ajax.css" type="text/css" />
{CSS}
<script src="includes/js/ajax-fade.js" type="text/javascript"></script>
{JAVASCRIPT}</head>
<body id="secure"{BODYOPTIONS}>
	<div id="shadow" class="shadow">&nbsp;</div>
	<div id="updating">Updating . . .</div>
	<div id="saved">Update Saved . . .</div>
	<div id="failed">Update Failed . . .</div>
{EXTRA}
<p class="skipnav"> <a class="skipnav" href="#maincontent">Skip Navigation</a> </p>

{HEADER}

<div id="red-header">
	<div class="clear">
		<h1>University of Nebraska&ndash;Lincoln</h1>
		<div id="breadcrumbs">
			{BADGE}
		</div>
	</div>
</div>
<!-- close red-header -->
<div id="container">
	<div class="clear">
		<div id="title"> <!-- InstanceBeginEditable name="collegenavigationlist" --> <!-- InstanceEndEditable -->
			<div id="titlegraphic">
				<!-- WDN: see glossary item 'title graphics' -->
				<!-- InstanceBeginEditable name="titlegraphic" -->
				<h1>Computer Help Center</h1>
				<h2>Check-in System</h2>
				<!-- InstanceEndEditable --></div>
			<!-- maintitle -->
		</div>
		<!-- close title -->
		
		<div id="navigation">
			<h4 id="sec_nav">Navigation</h4>
			<!-- InstanceBeginEditable name="navcontent" -->
			<div id="navlinks">
{NAVIGATION}
			</div>
			<!-- InstanceEndEditable -->
			<div id="nav_end"></div>
		</div>
		<!-- close navigation -->
		
		<div id="main_right" class="mainwrapper">
			<!--THIS IS THE MAIN CONTENT AREA; WDN: see glossary item 'main content area' -->
			
			<div id="maincontent"> <!-- InstanceBeginEditable name="maincontent" -->
				<?php virtual('/ucomm/templatedependents/templatesharedcode/includes/browsersniffers/noscript.html'); ?>
				<!--THIS IS THE MAIN CONTENT AREA; WDN: see glossary item 'main content area' -->
				<!-- TemplateBeginEditable name="maincontentarea" -->
{CONTENT}
				<div id="log" style="display:none;"></div>
				<!-- TemplateEndEditable -->
				<!--THIS IS THE END OF THE MAIN CONTENT AREA.-->
				<!-- InstanceEndEditable --> </div>
			 </div>
		<!-- close main right -->
	</div>
</div>
<!-- close container -->

<div id="footer">
	<div id="footer_floater"> <!-- InstanceBeginEditable name="optionalfooter" --> <!-- InstanceEndEditable -->
		<div id="copyright"> <!-- InstanceBeginEditable name="footercontent" -->
{FOOTER}
			<ul>
				<li><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a></li>
				<li><a href="http://validator.unl.edu/check/referer">W3C</a></li>
				<li><a href="http://www1.unl.edu/feeds/">RSS</a></li>
			</ul>
			<a href="http://www.unl.edu/" title="UNL Home"><img src="/ucomm/templatedependents/templatecss/images/wordmark.png" alt="UNL's wordmark" id="wordmark" /></a></div>
	</div>
</div>

<!-- close footer -->
<!-- sifr -->
<script type="text/javascript" src="/ucomm/templatedependents/templatesharedcode/scripts/sifr_replacements.js"></script>
</body>
<!-- InstanceEnd --></html>
