<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" ><!-- InstanceBegin template="/Templates/php.unlstandardtemplate.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<!-- InstanceBeginEditable name="doctitle" -->
<title>MyCHC.unl.edu - {TITLE}</title>
<link rel="stylesheet" type="text/css" media="screen" href="/ucomm/templatedependents/templatecss/layouts/main.css" />
<link rel="stylesheet" type="text/css" media="print" href="/ucomm/templatedependents/templatecss/layouts/print.css"/>
<script type="text/javascript" src="/ucomm/templatedependents/templatesharedcode/scripts/all_compressed.js"></script>

{WEBDEVHEADERS}
<link rel="stylesheet" type="text/css" media="screen" href="/ucomm/templatedependents/templatecss/layouts/secure.css"/>
<link rel="stylesheet" href="/includes/css/main-style.css" type="text/css" />
<link rel="stylesheet" href="includes/css/main-ajax.css" type="text/css" />
{CSS}
<script src="includes/js/ajax-fade.js" type="text/javascript"></script>
{JAVASCRIPT}</head>
<body id="secure" class="liquid"{BODYOPTIONS}>
	<div id="shadow" class="shadow">&nbsp;</div>
	<div id="saved">Update Saved . . .</div>
	<div id="failed">Update Failed . . .</div>
<p class="skipnav"> <a class="skipnav" href="#maincontent">Skip Navigation</a> </p>

{HEADER}

<div id="red-header">
	<div class="clear">
		<h1>University of Nebraska&ndash;Lincoln</h1>
		<div id="breadcrumbs">
			<!-- WDN: see glossary item 'breadcrumbs' -->
			<ul>
				<li class="first"><a href="http://www.unl.edu/">UNL</a></li>
				<li><a href="is.unl.edu">Information Services</a></li>
				<li><a href="http://ischc.unl.edu/">Computer Help Center</a></li>
				<li>Check-in System</li>
			</ul>
			{BADGE}
		</div>
	</div>
</div>
<!-- close red-header -->
<div id="container">
	<div class="clear">
		<div id="title">
			<div id="titlegraphic">
				<!-- WDN: see glossary item 'title graphics' -->
				<h1>Information Services</h1>
				<h2>Computer Help Center</h2>
			</div>
			<!-- maintitle -->
		</div>
		<!-- close title -->
		
		<div id="navigation">
			<h4 id="sec_nav">Navigation</h4>
			<!-- InstanceBeginEditable name="navcontent" -->
			<div id="navlinks">
{NAVIGATION}
			</div>
			<!-- InstanceEndEditable -->
			<div id="nav_end"></div>
		</div>
		
		<div id="main_right" class="mainwrapper">
			<!--THIS IS THE MAIN CONTENT AREA; WDN: see glossary item 'main content area' -->
			
			<div id="maincontent">
{CONTENT}
			</div>
		</div>
	</div>
	<div id="log" style="display:none;">
	</div>
</div>

<div id="footer">
	<div id="footer_floater">
		<div id="copyright">
{FOOTER}
			<ul>
				<li><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a></li>
				<li><a href="http://validator.unl.edu/check/referer">W3C</a></li>
				<li><a href="http://www1.unl.edu/feeds/">RSS</a></li>
			</ul>
			<a href="http://www.unl.edu/" title="UNL Home"><img src="/ucomm/templatedependents/templatecss/images/wordmark.png" alt="UNL's wordmark" id="wordmark" /></a></div>
	</div>
</div>
<script type="text/javascript" src="/ucomm/templatedependents/templatesharedcode/scripts/sifr_replacements.js"></script>
</body>
</html>
