		<div class="row">
			<div id="{CID}" class="cell" style="width:100%; background-color:{ROWCOLOR};">
				<div class="cell" style="width:5%">
					<input type="checkbox"{ACTIVE}>
				</div>
				<div class="cell" style="width:25%">
					{DATA}
				</div>
				<div class="cell" style="width:25%">
{LOCATIONSELECT}				</div>
				<!--<div class="cell" style="width:20%">
					{BRAND}
				</div>
				<div class="cell" style="width:15%">
					{TYPE}
				</div>
				<div class="cell" style="width:10%">
					{LOCATION}
				</div>-->
			</div>
		</div>
