	<div class="row top_space">
		<div class="cell header bottom_border" style="width:100%">
			<div class="cell">{NAME}</div>
			<div class="cell" style="float:right;"><input type="button" value="+" /></div>
		</div>
	</div>
	<div id="{SHORTNAME}" class="{HIDESHOWCLASS}">
<!--		<div class="row">
			<div class="cell header" style="width:5%">&nbsp;</div>
			<div class="cell header" style="width:25%"></div>
			<div class="cell header" style="width:25%">In Date</div>
			<div class="cell header" style="width:20%">Brand</div>
			<div class="cell header" style="width:15%">Type</div>
			<div class="cell header" style="width:10%">Location</div>
		</div>-->
{CONTACTS}	</div>
