	<div class="row top_space">
		<div class="cell header bottom_border" style="width:100%">
			<div class="cell">{LONGNAME}</div>
		</div>
	</div>
	<div id="{SHORTNAME}" class="{HIDESHOWCLASS}">
		<div class="row">
			<div class="cell header" style="width:5%">#</div>
			<div class="cell header" style="width:25%">TID</div>
			<div class="cell header" style="width:25%">In Date</div>
			<div class="cell header" style="width:20%">Brand</div>
			<div class="cell header" style="width:15%">Type</div>
			<div class="cell header" style="width:10%">Location</div>
		</div>
{COMPUTERS}	</div>
