	<div class="row top_space cell zenbox cool">
		<h3>{LONGNAME}</h3>
		<div class="row_wide">
			<div class="cell header" style="width:5%">#</div>
			<div class="cell header" style="width:25%">TID</div>
			<div class="cell header" style="width:25%">In Date</div>
			<div class="cell header" style="width:20%">Brand</div>
			<div class="cell header" style="width:15%">Type</div>
			<div class="cell header" style="width:10%">Location</div>
		</div>
{COMPUTERS}	</div>
