		<div class="row_wide">
			<div id="{TICKETNUM}" class="cell" style="width:100%; background-color:{ROWCOLOR};">
				<div class="cell" style="width:5%">
					{ROWNUM}
				</div>
				<div class="cell" style="width:25%">
					<a href="ticket_detail.php?tid={TID}">{TICKETNUM}</a>
				</div>
				<div class="cell" style="width:25%">
					{DATE}
				</div>
				<div class="cell" style="width:20%">
					{BRAND}
				</div>
				<div class="cell" style="width:15%">
					{TYPE}
				</div>
				<div class="cell" style="width:10%">
					{LOCATION}
				</div>
			</div>
		</div>
